version: '1'
services:
  app1:
    build: .
    image: uku_docker_task_6_image
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - ANOTHER_APP_ADDRESS=http://172.30.0.3:8081
    networks:
      uku_docker_task_6:
        ipv4_address: 172.30.0.2
  app2:
    build: .
    image: uku_docker_task_6_image
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - ANOTHER_APP_ADDRESS=http://172.30.0.2:8080
    networks:
      uku_docker_task_6:
        ipv4_address: 172.30.0.3
networks:
  uku_docker_task_6:
    name: uku_docker_task_6_network
    ipam:
      config:
        - subnet: 172.30.0.0/16